### ISSUE TITLE
As a User, I want a better button to create a movement, to improve UI flow.

### ISSUE THREAD

**Issue by marickmanrho** [GridtNetwork/gridt-client#114]
Now the create a movement button is an almost hidden plus icon to the right of the page. No other page has UI elements there and therefore the placement is awkward. Also it is good to give it a color so that you don't have to search for it that much.

**Comment by asharonbaltazar** [comment]
Hello, can I please a screenshot so I can have a better idea of what you mean?

**Comment by Drvanon** [comment]
Hello and welcome @asharonbaltazar! Our application is deployed on [app.gridt.org](http://app.gridt.org) where you can register (right now we are not doing much with the emails, feel free to use a fake one). When logged in you can go to movements by clicking on the hamburger menu in the top left corner and then clicking movements. On this page you can create a new movement by clicking the '+' icon in the top right corner:
![ashbar](https://user-images.githubusercontent.com/1318056/92413659-5fcae980-f151-11ea-84e2-43db2e391818.png)
This button is rather inconspicuous and can lead to confusion when looking for it. If you have a suggestion for how to fix this you can make a suggestion or even fork the application and creating a pull request.

**Comment by asharonbaltazar** [comment]
I can try my hand at it.

**Comment by asharonbaltazar** [comment]
Hello, 

I'm trying to implement a solution that doesn't clash with the application (e.g. add color etc), but how does this suggestion look to you? 

![image](https://user-images.githubusercontent.com/58940073/92415330-04333880-f11e-11ea-9171-4297b3f331b9.png)

Perhaps having movement in the top bar twice isn't the best, but I'd like your input nevertheless

**Comment by Drvanon** [comment]
Thank you for taking into consideration previous work on the application. The text clarifies a lot, so I guess that does the job quite well. Something that I was considering as well was those big round plus buttons floating at the top bottom corner. Apparently ionic refers to these as FAB buttons. 

Either option could work for me, but feel free to test both out and argue your point.

**Comment by asharonbaltazar** [comment]
Top-menu button works for both desktop and mobile — it is stationary and doesn't move around due to screen size.

![image](https://user-images.githubusercontent.com/58940073/92417968-b83ac080-f12a-11ea-8e3f-3e7ccf20f477.png)

FAB works mainly for mobile and is a colorful touch — however, it fails to adapt to larger screens.

**On mobile:** 
![image](https://user-images.githubusercontent.com/58940073/92417978-c1c42880-f12a-11ea-9381-666a5bc4406a.png)

**On desktop:**
![image](https://user-images.githubusercontent.com/58940073/92417980-c688dc80-f12a-11ea-98b5-7e30b79b3bd7.png)

**Comment by Yori-O92** [comment]
Hi @asharonbaltazar thank you for contributing! I like what you did. My suggestion would be to reduce the text 'add movement' to simply 'add', so it doesn't clash too much on small screens. Since the word already occurs on the same row, it should be intuitively clear. I don't mind the FAB button being a bit far away on the large screen, since our main focus is mobile screens.If you make a pull-request, please name your branch 'Issue-114-<short description>' (e.g.: 'Issue-114-addbutton') and request a merge with the branch called 'api-development' after you push, since this one is the most up-to-date (not the master branch).

Do you agree @Drvanon ?
Cheers

**Comment by Drvanon** [comment]
I agree that the sticking to the naming convention could be useful, although I do think it might be sensible to revisit it, because now all of our branches are starting with "Issue" and that is a little redundant. Maybe we should leave it at "<Issue number>-<Short Description>"?

**Comment by Yori-O92** [comment]
Sure! Anything that clearly indicates the issue and the modification. Enjoy pushing and pulling!
