### ISSUE TITLE
App components needs to be updated to new API

### ISSUE THREAD

**Issue by AndraUdrescu** [GridtNetwork/gridt-client#44]
https://github.com/GridtNetwork/gridt-client/blob/f57e2a2bc09eb201d3737f6155179ee7b7a5bede/gridt/src/app/app.component.ts#L52

**Comment by Drvanon** [comment]
Hi Andra, 
I know that you said this in a meeting that I was part of, but also that meeting was 2.5 hours long. I personally have forgotten what you meant by this. Would you mind writing out exactly what needs to be done so that we can be aware of it as well?

**Comment by AndraUdrescu** [comment]
Ah, this is a reminder. I have a tendency to forget about app.component and app.module since I don't work in them. I have sent 2 hours trying to figure what was wrong and the code was fine, I just forgot to make changes in app.module. Since this has old login code I marked that places to not forget that

**Comment by Drvanon** [comment]
Great to hear that you managed to resolve it. I would still really appreciate it if you could give this an appropriate title and description. 

GitHub issues are our way of documenting progress. For this reason we try to be very explicit in both the title and the description.

**Comment by AndraUdrescu** [comment]
I'll try to be explicit in my issues. The code still needs changes and I'll leave this open for now just as a reminder. This is more of a bookmark rather than an issue, thus the no description, needs changes thing. I really don't know if you can mark parts of code or not with GitHub

**Comment by Drvanon** [comment]
Thank you for understanding.

It is good that you leave the issue open if still more work needs to be done. Might I suggest however to make some changes? I would title this issue: "App components needs to be updated to new API." This way it becomes clear what the goal is in one short phrase so we all now what you are working on. Because you are working on this right now, it would be also cool if you could assign yourself this issue. In your description you also reference a piece of code by providing the github URL to the file. This way you can even show the exact piece of code that needs to change. If I remember correctly (and I very well might not), in the meeting you mentioned that you have to revisit the login logic there. In a description I would consequently write: "Due to changes in the way the client talks to the server the app component needs to keep track of the login status of the user in a different manner. It needs to be revisited to make sure it is fully up to date."

My reasoning for this explicit-ness is that as the developers of Gridt we are separated in both space _and_ time, making miscommunication extremely easy. We will have to put in effort to ensure the longevity of the project.

**Comment by AndraUdrescu** [comment]
I will make the changes, thanks for the tips.

**Comment by Drvanon** [comment]
In the above commit I have removed some code that referenced the old api, because I was doing some clean up and I thought I would just immediately replace it. You can compare it with a previous commit to check if I left out anything important.

**Comment by AndraUdrescu** [comment]
The changes are fine. The code should work
